import Head from "next/head";
import mockData from "@/mocks/restaurant-list";
import { ContentContainer } from "@/styles/pageStyles/index.styled";
import { RestaurantType } from "@/mocks/restaurant-api-response.type";
import { Grid4Cols } from "@/components/website-parts/Grid4Cols/Grid4Cols.styled";
import { RestaurantGridItem } from "@/components/website-parts/RestaurantGridItem/RestaurantGridItem";
import { Title1 } from "@/components/ui-components/Typography/Title1";
import { apiRestaurantResponseToArray } from "@/helpers/apiRestaurantResponseToArray";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { ComponentContainer } from "@/components/ui-components/ComponentContainer/ComponentContainer";
import { NextPageWithLayout } from "./_app";
import { DefaultLayout } from "@/layouts/defaultLayout/defaultLayout";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const Home: NextPageWithLayout<Props> = ({ restaurantList }) => {
  return (
    <>
      <Head>
        <title>Interactive Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <ContentContainer>
          <Title1 uppercase>Check out available restaurants</Title1>
          <Grid4Cols>
            {restaurantList?.map((restaurant) => (
              <RestaurantGridItem key={restaurant.id} restaurant={restaurant} />
            ))}
          </Grid4Cols>
        </ContentContainer>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page) {
  return (
    <DefaultLayout>
      <ComponentContainer>{page}</ComponentContainer>
    </DefaultLayout>
  );
};

interface StaticProps {
  restaurantList: RestaurantType[];
}

export const getStaticProps: GetStaticProps<StaticProps> = async () => {
  return {
    props: {
      restaurantList: apiRestaurantResponseToArray(mockData),
    },
  };
};

export default Home;
