import { Navbar } from "@/components/website-parts/Navbar/Navbar";
import { darkTheme, DARK_THEME, lightTheme } from "@/hooks/useTheme/themes";
import Head from "next/head";
import { ThemeProvider } from "styled-components";
import { useCurrentTheme, useTheme } from "@/hooks/useTheme/useTheme";
import { GlobalStyles } from "@/styles/global.styled";
import { SelectedThemeContext } from "@/hooks/useTheme/useTheme.context";

export default function Home() {
  return (
    <>
      <Head>
        <title>Interactive Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeProvider
          theme={useCurrentTheme() === DARK_THEME ? darkTheme : lightTheme}
        >
          <Navbar />
          <GlobalStyles />
        </ThemeProvider>
        <p>{useCurrentTheme()} from Home</p>
      </main>
    </>
  );
}
